# Generated by Django 3.2.18 on 2023-04-17 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_emote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emote_user',
            field=models.ManyToManyField(related_name='emote_articles', through='reviews.Emote', to=settings.AUTH_USER_MODEL),
        ),
    ]
